Add Thai language.
brentvollebregt/auto-py-to-exe pull request #247
Opened 2022-02-23 15:11 UTC by Teerut26

I have added Thai language so that Thai people can use it more conveniently.

2022-02-24 06:48 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +                th:'Output',
If the translation is not different to `en`, you can leave it out as `en` will be defaulted to.

2022-02-24 06:49 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +                th:'หนึ่งไฟล์',
To save me some time fixing these, can we put a space between `:` and `'`, e.g. ` th: 'หนึ่งไฟล์',`

2022-02-24 06:52 UTC, brentvollebregt requested changes
Looking good, just a couple of requests 👍 

Can you also add the translation to the table under "Translations" in the README?

2022-02-24 06:52 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +    },
Can you put this above Turkish (alphabetical)

2022-02-24 06:52 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +                th:'ตัวเลือกเฉพาะของ Windows และ Mac Os X'
Can we have a comma at the end (to reduce the diff for later changes)

2022-02-24 14:47 UTC, Teerut26 commented
I updated @brentvollebregt finish.

2022-02-25 08:22 UTC, brentvollebregt requested changes

2022-02-25 08:22 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +
This extra line is not needed

2022-02-25 08:22 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +                th:'เรียกดูโฟลเดอร์'
Missing a trailing comma (and some others)

2022-02-25 08:22 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +                th:'อื่นๆ'
Space between colon and quote (and some others)

2022-02-25 08:22 UTC, brentvollebregt commented on README.md
> +| Thai (ภาษาไทย)                              | [teerut26](https://github.com/teerut26)       | UI (99%)                             |
Can we have `UI (partial)` instead of `UI (99%)` to keep consistent. If you have a translation for "Output", then we can have just `UI`.

2022-02-25 11:18 UTC, Teerut26 commented
I updated @brentvollebregt

2022-02-25 22:47 UTC, merged

2022-02-25 23:00 UTC, brentvollebregt commented
This has been released as part of 2.18.0