Update i18n.js
brentvollebregt/auto-py-to-exe pull request #491
Opened 2024-05-30 15:28 UTC by Zmicier21

Add Belarusian language

2024-05-31 07:04 UTC, brentvollebregt requested changes
There is a [checklist for translations in this template](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/.github/PULL_REQUEST_TEMPLATE/translation.md) - I'll update the PR to have this checklist and you can go through it 👍 

Take a look at #355 if you need an example.

2024-05-31 07:04 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +  },
This need to go above Brazilian Portuguese

2024-05-31 07:04 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
I noticed the `ui.button.oneFile` translation is missing

2024-05-31 18:33 UTC, Zmicier21 commented on auto_py_to_exe/web/js/i18n.js
As I see it, there is a translation in that place

2024-05-31 22:47 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
My bad, for some reason it looked like it wasn't there

2024-05-31 22:48 UTC, brentvollebregt commented
Could you add an entry to the translations table in the README.md file? Other than that, this looks good.

2024-06-03 08:55 UTC, brentvollebregt commented
Hey, I see you have 5 branches in your repo with changes that appear they should be in `Zmicier21:patch-1` - do you need some help getting all these changes into this PR? Happy to move the commits around for you if you need.

2024-06-04 07:15 UTC, Zmicier21 commented
I don't understand, how use git correctly

2024-06-04 09:48 UTC, brentvollebregt requested changes
Looking great, just two more small things thanks.

> I don't understand, how use git correctly

No worries! I'm happy to help move commits around if you need.

2024-06-04 09:48 UTC, brentvollebregt commented on README.md
> +| Belarusian (Беларуская)                    | [Zmicier21](https://github.com/Zmicier21)            |          UI
```suggestion
| Belarusian (Беларуская)                     | [Zmicier21](https://github.com/Zmicier21)                                                    | UI                                   |
```

2024-06-04 09:48 UTC, brentvollebregt commented on README.md
Could you also add one line under "[Translations of This File](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/README.md?plain=1#L17)" now that you have translated the README 😃

2024-06-05 09:10 UTC, brentvollebregt approved these changes
Just tidied the last couple of things up for you - looks good to go. Thank you for your contribution!

2024-06-05 09:11 UTC, merged

2024-06-05 09:24 UTC, brentvollebregt commented
Thanks for the contribution! This has been released in [v2.44.0](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.44.0) 🚀