slovak translation
brentvollebregt/auto-py-to-exe pull request #514
Opened 2024-12-21 14:38 UTC by mostypc123

**Summary**

_Insert a brief description about what your change is / does._
I added a translation to slovak.

> If this is related to an issue, please link the issue here

**Translation checklist**

- [x] I have ran the application to make sure my code runs
- [x] I have used the correct [ISO 639-1 code](https://www.alchemysoftware.com/livedocs/ezscript/Topics/Catalyst/Language.htm) for my translations (e.g. `en`)
- [x] I have formatted all changes as described in the [contribution style guide](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/CONTRIBUTING.md#style-guide)
- [x] I have added the language to `supportedLanguages` in alphabetical order
- [x] I have added the language to the table in [README.md](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/README.md#translations) in alphabetical order

2024-12-23 13:46 UTC, mostypc123 commented
@brentvollebregt please review the pr

2024-12-26 02:25 UTC, brentvollebregt commented
Apologies for the delay - I don't have something I can review this properly right now but it looks like the prettier formatting check failed. 

Other than that, this is looking ok from what I can see currently👍

2024-12-26 08:11 UTC, mostypc123 commented
idk why but i formatted it two times with prettier, or do i need more config after ibstalling the vs code extension

2024-12-26 08:50 UTC, brentvollebregt commented
What are you using to format? I used `npx prettier@2.8.8 --write .` on your branch as described in the contribution guidelines and it fixed the formatting issues.

2024-12-26 08:51 UTC, mostypc123 commented
i used the vscode extension

2024-12-26 08:52 UTC, brentvollebregt commented
Please use `npx prettier@2.8.8 --write .` as described in the [contribution style guide](https://github.com/brentvollebregt/auto-py-to-exe/blob/master/CONTRIBUTING.md#style-guide) (on the PR checklist)

2024-12-26 08:55 UTC, brentvollebregt commented
I have the changes locally now - I'll push them for you

2024-12-26 08:56 UTC, mostypc123 commented
thanks

2024-12-26 09:04 UTC, brentvollebregt requested changes

2024-12-26 09:04 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +  },
You have checked " I have added the language to `supportedLanguages` in alphabetical order" but this is not. It should be under Serbian.

2024-12-26 09:04 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +        sk: 'Špecifické nastavenia ${applicationName}',
The variable is not being inserted correctly

```suggestion
        sk: `Špecifické nastavenia ${applicationName}`,
```

2024-12-26 09:04 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
> +          '<a ${onFileModeAdditionalFilesHelpAnchorTagContents}>prečítajte si tento príspevok (stránka v angličtine)</a>\n' +
The variable is not being inserted

```suggestion
         `<a ${onFileModeAdditionalFilesHelpAnchorTagContents}>prečítajte si tento príspevok (stránka v angličtine)</a>\n` +
```

2024-12-26 09:09 UTC, mostypc123 commented
will do the things later im on github mobile right now idk how to even use it😂

2024-12-26 09:11 UTC, mostypc123 commented
looks like i figured it out, it's fixed

2024-12-26 09:12 UTC, brentvollebregt requested changes

2024-12-26 09:12 UTC, brentvollebregt commented on auto_py_to_exe/web/js/i18n.js
>    {
Looks like this will fail to parse as it's missing a comma

2024-12-26 09:23 UTC, brentvollebregt approved these changes

2024-12-26 09:23 UTC, merged

2024-12-26 09:29 UTC, brentvollebregt commented
Thanks for the contribution! This has been released in [v2.45.1](https://github.com/brentvollebregt/auto-py-to-exe/releases/tag/v2.45.1) 🚀